version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  gateway:
    build:
      context: ./Gateway.Api
    ports:
      - "5000:80"
    depends_on:
      - sent1
      - sent2
      - deleted

  sent1:
    build:
      context: ./Sent1.Api
    ports:
      - "5099:80"

  sent2:
    build:
      context: ./Sent2.Api
    ports:
      - "5217:80"

  deleted:
    build:
      context: ./Deleted.Api
    ports:
      - "5021:80"

  inbox1:
    build:
      context: ./Inbox.Api
    ports:
      - "6001:80"

  inbox2:
    build:
      context: ./Inbox.Api
    ports:
      - "6002:80"

  loadbalancer:
    build:
      context: ./Loadbalancer
    ports:
      - "5102:80"
    depends_on:
      - inbox1
      - inbox2
