version: '3.9'

services:
  gateway:
    image: searchengine-gateway
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - sent1
      - sent2
      - deleted

  sent1:
    image: searchengine-sent1
    build:
      context: .
      dockerfile: Sent1.Api/Dockerfile  # tidligere Snippets.Api
    ports:
      - "5099:80"

  sent2:
    image: searchengine-sent2
    build:
      context: .
      dockerfile: Sent2.Api/Dockerfile  # tidligere Sent.Api
    ports:
      - "5217:80"

  deleted:
    image: searchengine-deleted
    build:
      context: .
      dockerfile: Deleted.Api/Dockerfile
    ports:
      - "5021:80"

  loadbalancer:
    image: searchengine-loadbalancer
    build:
      context: .
      dockerfile: Loadbalancer/Dockerfile
    ports:
      - "5102:80"
    depends_on:
      - inbox1
      - inbox2

  inbox1:
    image: searchengine-inbox1
    build:
      context: .
      dockerfile: Inbox.Api/Dockerfile
    ports:
      - "6001:80"

  inbox2:
    image: searchengine-inbox2
    build:
      context: .
      dockerfile: Inbox.Api/Dockerfile
    ports:
      - "6002:80"

  redis:
    image: redis
    ports:
      - "6379:6379"
