version: '3.9'

services:
  gateway:
    image: searchengine-gateway
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    ports:
      - "5100:8080"
    depends_on:
      - sent1
      - sent2
      - deleted

  sent1:
    image: searchengine-sent1
    build:
      context: .
      dockerfile: Sent1.Api/Dockerfile  # tidligere Snippets.Api
    ports:
      - "5099:80"
    volumes:
      - C:/Users/Axelb/OneDrive/Skrivebord/medium/allen-p/_sent_mail:/app/_sent_mail

  sent2:
    image: searchengine-sent2
    build:
      context: .
      dockerfile: Sent2.Api/Dockerfile  # tidligere Sent.Api
    ports:
      - "5217:80"
    volumes:
      - C:/Users/Axelb/OneDrive/Skrivebord/medium/allen-p/_sent_mail:/app/_sent_mail

  deleted:
    image: searchengine-deleted
    build:
      context: .
      dockerfile: Deleted.Api/Dockerfile
    ports:
      - "5021:80"
    volumes:
      - C:/Users/Axelb/OneDrive/Skrivebord/medium/allen-p/deleted_items:/app/deleted_items

  loadbalancer:
    image: searchengine-loadbalancer
    build:
      context: .
      dockerfile: Loadbalancer/Dockerfile
    ports:
      - "5102:80"
    depends_on:
      - inbox1
      - inbox2

  inbox1:
    image: searchengine-inbox1
    build:
      context: .
      dockerfile: Inbox.Api/Dockerfile
    ports:
      - "6001:80"
    volumes:
      - C:/Users/Axelb/OneDrive/Skrivebord/medium/allen-p/inbox:/app/inbox

  inbox2:
    image: searchengine-inbox2
    build:
      context: .
      dockerfile: Inbox.Api/Dockerfile
    ports:
      - "6002:80"
    volumes:
      - C:/Users/Axelb/OneDrive/Skrivebord/medium/allen-p/inbox:/app/inbox

  redis:
    image: redis
    ports:
      - "6379:6379"
